In [1]:
%load_ext autoreload
%autoreload 2
%load_ext rich
from pyuncertainnumber import pba
import numpy as np
from rich import print

# scalar interval

- it can be checked if a scalar interval using the property `scalar`

In [ ]:
x = pba.I(1,2)
x

In [ ]:
x.val

In [ ]:
x.to_numpy()

In [ ]:
x.scalar

In [ ]:
x.shape

In [ ]:
len(x)

In [ ]:
x.ndim

In [ ]:
x_ = pba.I([1], [2])

In [ ]:
x_

In [ ]:
x_.unsized

In [ ]:
x_.shape

In [ ]:
x_.ndim

In [ ]:
x_.shape

# array-like intervals

## vector interval

In [2]:
x = pba.I(lo=[1,2,3,4],hi=[2,3,4,5])
x


[1.0,2.0]
[2.0,3.0]
[3.0,4.0]
[4.0,5.0]

In [3]:
x.shape

(4,)

In [4]:
x.ndim

1

In [5]:
x.scalar

False

In [6]:
# vec-interval being iterable
for i in x:
    print(f"element: {i}")

element: [1.0,2.0]

element: [2.0,3.0]

element: [3.0,4.0]

element: [4.0,5.0]

In [7]:
# intervalise

# say I have a list of list

In [8]:
x.to_numpy()


array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [4., 5.]])

In [9]:
arr = x.val
arr


array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [4., 5.]])

In [10]:
list(arr)

[array([1., 2.]), array([2., 3.]), array([3., 4.]), array([4., 5.])]

In [11]:
arr.shape

(4, 2)

In [12]:
new_x = pba.intervalise(arr)
new_x


[1.0,2.0]
[2.0,3.0]
[3.0,4.0]
[4.0,5.0]

In [13]:
# list
list_arr = [[1., 2.], 
 [2., 3.], 
 [3., 4.], 
 [4., 5.]
]

In [14]:
list_arr

[[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0]]

In [15]:
pba.intervalise(list_arr)


[1.0,2.0]
[2.0,3.0]
[3.0,4.0]
[4.0,5.0]

In [16]:
list_arr[3]

[4.0, 5.0]

#### **split intervals** (novel) acomplished

In [17]:
list_of_scalar_intervals = [pba.intervalise(item) for item in list_arr]
list_of_scalar_intervals

[[1.0,2.0], [2.0,3.0], [3.0,4.0], [4.0,5.0]]

In [18]:
v = pba.intervalise(list_of_scalar_intervals)

In [19]:
v.shape

(4,)

In [20]:
y = pba.I(1,2)

In [21]:
from pyuncertainnumber import make_vec_interval

In [22]:
v2 = make_vec_interval(list_of_scalar_intervals)

In [23]:
v2.shape

(4,)

In [24]:
v == v2

array([ True,  True,  True,  True])

In [27]:
from pyuncertainnumber.pba.intervals.methods import unpack

In [ ]:
# successful
l_v = unpack(v)

## matrix interval

In [32]:
a = [[[1,2], [2,3], [4,5]],
      [[-1,2],[-2,1],[3,5]],
      [[0,2], [3,4], [6,8]]]

In [34]:
a = np.array(a)
a


array([[[ 1,  2],
        [ 2,  3],
        [ 4,  5]],

       [[-1,  2],
        [-2,  1],
        [ 3,  5]],

       [[ 0,  2],
        [ 3,  4],
        [ 6,  8]]])

In [35]:
a.shape

(3, 3, 2)

In [36]:
a_i = pba.intervalise(a)

In [37]:
a_i


[1. 2.] [2. 3.] [4. 5.]
[-1.  2.] [-2.  1.] [3. 5.]
[0. 2.] [3. 4.] [6. 8.]

In [39]:
a_i.shape

(3, 3)

In [40]:
a_i.ndim

2

In [42]:
# for item in a_i:
#     print(item)

In [43]:
unpack(a_i)

[[1.0,2.0], [2.0,3.0], [4.0,5.0], [-1.0,2.0], [-2.0,1.0], [3.0,5.0], [0.0,2.0], [3.0,4.0], [6.0,8.0]]

In [44]:
a_i * 2


[2. 4.] [4. 6.] [ 8. 10.]
[-2.  4.] [-4.  2.] [ 6. 10.]
[0. 4.] [6. 8.] [12. 16.]

In [46]:
a_i[0,2]

[4.0,5.0]

In [50]:
# row-wise python looping
n, d = a_i.shape

for ind in np.arange(n):
    print(f"each row: {a_i[ind, :]}")

each row: [1.0,2.0]
[2.0,3.0]
[4.0,5.0]

each row: [-1.0,2.0]
[-2.0,1.0]
[3.0,5.0]

each row: [0.0,2.0]
[3.0,4.0]
[6.0,8.0]